In [1]:
import torch

In [2]:
x = torch.Tensor([5,3])
y = torch.Tensor([2,1])

print(x*y)

tensor([10.,  3.])


In [3]:
z = torch.rand([2,5])
print(z)

tensor([[0.5920, 0.7657, 0.3899, 0.8838, 0.1090],
        [0.3020, 0.3987, 0.8565, 0.4369, 0.7559]])


In [6]:
z = z.view([1,10])
z

tensor([[0.5920, 0.7657, 0.3899, 0.8838, 0.1090, 0.3020, 0.3987, 0.8565, 0.4369,
         0.7559]])